apiVersion: v1
kind: ConfigMap
metadata:
  name: qa-test-config
  namespace: qa-automation
data:
  HEADLESS: "true"
  BASE_URL: "https://www.saucedemo.com"
  API_BASE_URL: "https://jsonplaceholder.typicode.com"
  LOG_LEVEL: "INFO"
  PYTHONUNBUFFERED: "1"
